config/routes.rb
Rails.application.routes.draw do
  resources :consoles
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/console.rb
class Console < ApplicationRecord
end

app/models/game.rb
class Game < ApplicationRecord
    validates :title, presence: true  
    validates :img1, presence: true   
    validates :img2, presence: true   

 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/consoles_controller.rb
class ConsolesController < ApplicationController
  before_action :set_console, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /consoles
  # GET /consoles.json
  def index
    @consoles = Console.all
  end

  # GET /consoles/1
  # GET /consoles/1.json
  def show
  end

  # GET /consoles/new
  def new
    @console = Console.new
  end

  # GET /consoles/1/edit
  def edit
  end

  # POST /consoles
  # POST /consoles.json
  def create
    @console = Console.new(console_params)

    respond_to do |format|
      if @console.save
        format.html { redirect_to @console, notice: 'Console was successfully created.' }
        format.json { render :show, status: :created, location: @console }
      else
        format.html { render :new }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consoles/1
  # PATCH/PUT /consoles/1.json
  def update
    respond_to do |format|
      if @console.update(console_params)
        format.html { redirect_to @console, notice: 'Console was successfully updated.' }
        format.json { render :show, status: :ok, location: @console }
      else
        format.html { render :edit }
        format.json { render json: @console.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consoles/1
  # DELETE /consoles/1.json
  def destroy
    @console.destroy
    respond_to do |format|
      format.html { redirect_to consoles_url, notice: 'Console was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_console
      @console = Console.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def console_params
      params.require(:console).permit(:title, :img1, :img2, :img3, :img4, :video1, :video2, :platform, :emu, :system, :price, :buy, :about, :info)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:title, :img1, :img2, :img3, :img4, :video1, :video2, :aboutgame, :platform, :genre, :hitnt, :try, :buy)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/consoles_helper.rb
module ConsolesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/consoles/_form.html.erb
<%= form_with(model: console, local: true) do |form| %>
  <% if console.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(console.errors.count, "error") %> prohibited this console from being saved:</h2>

      <ul>
      <% console.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :img1 %>
    <%= form.text_field :img1 %>
  </div>

  <div class="field">
    <%= form.label :img2 %>
    <%= form.text_field :img2 %>
  </div>

  <div class="field">
    <%= form.label :img3 %>
    <%= form.text_field :img3 %>
  </div>

  <div class="field">
    <%= form.label :img4 %>
    <%= form.text_field :img4 %>
  </div>

  <div class="field">
    <%= form.label :video1 %>
    <%= form.text_field :video1 %>
  </div>

  <div class="field">
    <%= form.label :video2 %>
    <%= form.text_field :video2 %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <div class="field">
    <%= form.label :emu %>
    <%= form.text_field :emu %>
  </div>

  <div class="field">
    <%= form.label :system %>
    <%= form.text_field :system %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :buy %>
    <%= form.text_field :buy %>
  </div>

  <div class="field">
    <%= form.label :about %>
    <%= form.text_field :about %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/consoles/edit.html.erb
<h1>Editing Console</h1>

<%= render 'form', console: @console %>

<%= link_to 'Show', @console %> |
<%= link_to 'Back', consoles_path %>

app/views/consoles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consoles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img1</th>
      <th>Img2</th>
      <th>Img3</th>
      <th>Img4</th>
      <th>Video1</th>
      <th>Video2</th>
      <th>Platform</th>
      <th>Emu</th>
      <th>System</th>
      <th>Price</th>
      <th>Buy</th>
      <th>About</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consoles.each do |console| %>
      <tr>
        <td><%= console.title %></td>
        <td><%= console.img1 %></td>
        <td><%= console.img2 %></td>
        <td><%= console.img3 %></td>
        <td><%= console.img4 %></td>
        <td><%= console.video1 %></td>
        <td><%= console.video2 %></td>
        <td><%= console.platform %></td>
        <td><%= console.emu %></td>
        <td><%= console.system %></td>
        <td><%= console.price %></td>
        <td><%= console.buy %></td>
        <td><%= console.about %></td>
        <td><%= console.info %></td>
        <td><%= link_to 'Show', console %></td>
        <td><%= link_to 'Edit', edit_console_path(console) %></td>
        <td><%= link_to 'Destroy', console, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Console', new_console_path %>

app/views/consoles/new.html.erb
<h1>New Console</h1>

<%= render 'form', console: @console %>

<%= link_to 'Back', consoles_path %>

app/views/consoles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @console.title %>
</p>

<p>
  <strong>Img1:</strong>
  <%= @console.img1 %>
</p>

<p>
  <strong>Img2:</strong>
  <%= @console.img2 %>
</p>

<p>
  <strong>Img3:</strong>
  <%= @console.img3 %>
</p>

<p>
  <strong>Img4:</strong>
  <%= @console.img4 %>
</p>

<p>
  <strong>Video1:</strong>
  <%= @console.video1 %>
</p>

<p>
  <strong>Video2:</strong>
  <%= @console.video2 %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @console.platform %>
</p>

<p>
  <strong>Emu:</strong>
  <%= @console.emu %>
</p>

<p>
  <strong>System:</strong>
  <%= @console.system %>
</p>

<p>
  <strong>Price:</strong>
  <%= @console.price %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @console.buy %>
</p>

<p>
  <strong>About:</strong>
  <%= @console.about %>
</p>

<p>
  <strong>Info:</strong>
  <%= @console.info %>
</p>

<%= link_to 'Edit', edit_console_path(@console) %> |
<%= link_to 'Back', consoles_path %>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :img1 %>
    <%= form.text_field :img1 %>
  </div>

  <div class="field">
    <%= form.label :img2 %>
    <%= form.text_field :img2 %>
  </div>

  <div class="field">
    <%= form.label :img3 %>
    <%= form.text_field :img3 %>
  </div>

  <div class="field">
    <%= form.label :img4 %>
    <%= form.text_field :img4 %>
  </div>

  <div class="field">
    <%= form.label :video1 %>
    <%= form.text_field :video1 %>
  </div>

  <div class="field">
    <%= form.label :video2 %>
    <%= form.text_field :video2 %>
  </div>

  <div class="field">
    <%= form.label :aboutgame %>
    <%= form.text_field :aboutgame %>
  </div>

  <div class="field">
    <%= form.label :platform %>
    <%= form.text_field :platform %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :hitnt %>
    <%= form.text_field :hitnt %>
  </div>

  <div class="field">
    <%= form.label :try %>
    <%= form.text_field :try %>
  </div>

  <div class="field">
    <%= form.label :buy %>
    <%= form.text_field :buy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img1</th>
      <th>Img2</th>
      <th>Img3</th>
      <th>Img4</th>
      <th>Video1</th>
      <th>Video2</th>
      <th>Aboutgame</th>
      <th>Platform</th>
      <th>Genre</th>
      <th>Hitnt</th>
      <th>Try</th>
      <th>Buy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.img1 %></td>
        <td><%= game.img2 %></td>
        <td><%= game.img3 %></td>
        <td><%= game.img4 %></td>
        <td><%= game.video1 %></td>
        <td><%= game.video2 %></td>
        <td><%= game.aboutgame %></td>
        <td><%= game.platform %></td>
        <td><%= game.genre %></td>
        <td><%= game.hitnt %></td>
        <td><%= game.try %></td>
        <td><%= game.buy %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @game.title %>
</p>

<p>
  <strong>Img1:</strong>
  <%= @game.img1 %>
</p>

<p>
  <strong>Img2:</strong>
  <%= @game.img2 %>
</p>

<p>
  <strong>Img3:</strong>
  <%= @game.img3 %>
</p>

<p>
  <strong>Img4:</strong>
  <%= @game.img4 %>
</p>

<p>
  <strong>Video1:</strong>
  <%= @game.video1 %>
</p>

<p>
  <strong>Video2:</strong>
  <%= @game.video2 %>
</p>

<p>
  <strong>Aboutgame:</strong>
  <%= @game.aboutgame %>
</p>

<p>
  <strong>Platform:</strong>
  <%= @game.platform %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @game.genre %>
</p>

<p>
  <strong>Hitnt:</strong>
  <%= @game.hitnt %>
</p>

<p>
  <strong>Try:</strong>
  <%= @game.try %>
</p>

<p>
  <strong>Buy:</strong>
  <%= @game.buy %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shutdown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>